name: Build and Test
on: [push]

runs-on: ubuntu-latest

jobs:
    build:
        name: Build
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Setup Python 3.7
              uses: actions/setup-python@v1
              with:
                python-version: 3.7
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install .
    test:
        name: Test
        needs: build
        steps:
            - name: Run Unit Tests
              run: |
                python -m unittest discover -p "**/tests/*.py" -v